name: sana_dictionary
description: A Flutter app for explaining Arabic words from an Express API.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.5
  json_annotation: ^4.4.0
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  connectivity_plus: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  json_serializable: ^6.1.5
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Hayah
      fonts:
        - asset: assets/fonts/hayah.otf
